apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/sqlserver.yaml
  - k8s/sqlserver-secret.yaml
  - k8s/redis.yaml
  - k8s/redis-secret.yaml
  - k8s/jwt-secret.yaml
  - k8s/backend.yaml
  - k8s/frontend.yaml

configMapGenerator:
  - name: mssql-init-scripts
    files:
      - sql-scripts/init-db.sh
      - sql-scripts/init.sql
