apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: docker.io/library/lookgo-busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until nc -z backend-service 8080; do echo waiting for backend-service; sleep 2; done",
            ]
      containers:
        - name: frontend
          image: docker.io/library/lookgo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: DNS_RESOLVER
              value: "kube-dns.kube-system.svc.cluster.local" # 確保 hostname 可以被正確解析、拿到 CoreDNS 位址
            - name: BACKEND_URL
              value: "backend-service.default.svc.cluster.local:8080" # 用完整 FQDN ，不能用短名稱
            - name: NPM_RC_FILE
              value: "settings-nexus.xml"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
