apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/redis
