apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: docker.io/library/lookgo-sqlserver-simple:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: sa-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: db-password
          livenessProbe:
            initialDelaySeconds: 40
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
